name: test

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
          cache: 'gradle'

      - name: setup gradle
        uses: gradle/gradle-build-action@v2

      - name: test
        working-directory: simpledb
        run: ./gradlew test

      - name: run
        working-directory: simpledb
        run: ./gradlew run

      - name: embeddedclient
        working-directory: simpledb
        run: |
          rm -rf datadir
          ./gradlew embeddedclient
